#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 26 16:07:20 2019

@author: janbieniek
"""
def f(a,b):
    return a+b

def dict_interdiff(d1, d2):
    '''
    d1, d2: dicts whose keys and values are integers
    Returns a tuple of dictionaries according to the instructions above
    '''
    dict1 = {}
    dict2 = {}
    
    for element in d1:
        if not element in d2:
            dict2[element] = d1[element]
        else:
            dict1[element] = f(d1[element],d2[element])
            
    for element in d2:
        if not element in d1:
            dict2[element] = d2[element]
    
    return (dict1,dict2)
            
            
